Repository verdaccio/website, pull requests merged in 2019-10, with the labels that each got.

#188 feat: add blog release 4.3.0
  website/blog/2019-09-30-verdaccio-430-release.md
Labels: wip

#126 feat: add agent_options to uplink configuration doc
  docs/uplinks.md
Labels: depends on, hacktoberfest 🎃

#195 chore: add blog post verdaccio with verdaccio-ldap and docker
  website/blog/2019-10-05-verdaccio-4-with-ldap-and-docker.md
Labels: hacktoberfest 🎃

#201 Add Forwarded-Proto missing headers
  docs/reverse-proxy.md
Labels: hacktoberfest 🎃

#207 Fix typo
  docs/security-policy.md
Labels: hacktoberfest 🎃
